LINK = 'http://data.gdeltproject.org/events/'

COLUMNS = [
    'GLOBALEVENTID','SQLDATE','MONTHYEAR','YEAR','FRACTIONDATE',
    'ACTOR1CODE','ACTOR1NAME','ACTOR1COUNTRYCODE','ACTOR1KNOWNGROUPCODE','ACTOR1ETHNICCODE','ACTOR1RELIGION1CODE','ACTOR1RELIGION2CODE','ACTOR1TYPE1CODE','ACTOR1TYPE2CODE','ACTOR1TYPE3CODE',
    'ACTOR2CODE','ACTOR2NAME','ACTOR2COUNTRYCODE','ACTOR2KNOWNGROUPCODE','ACTOR2ETHNICCODE','ACTOR2RELIGION1CODE','ACTOR2RELIGION2CODE','ACTOR2TYPE1CODE','ACTOR2TYPE2CODE','ACTOR2TYPE3CODE',
    'ISROOTEVENT','EVENTCODE','EVENTBASECODE','EVENTROOTCODE','QUADCLASS','GOLDSTEINSCALE',
    'NUMMENTIONS','NUMSOURCES','NUMARTICLES','AVGTONE',
    'ACTOR1GEO_TYPE','ACTOR1GEO_FULLNAME','ACTOR1GEO_COUNTRYCODE','ACTOR1GEO_ADM1CODE','ACTOR1GEO_LAT','ACTOR1GEO_LONG','ACTOR1GEO_FEATUREID',
    'ACTOR2GEO_TYPE','ACTOR2GEO_FULLNAME','ACTOR2GEO_COUNTRYCODE','ACTOR2GEO_ADM1CODE','ACTOR2GEO_LAT','ACTOR2GEO_LONG','ACTOR2GEO_FEATUREID',
    'ACTIONGEO_TYPE','ACTIONGEO_FULLNAME','ACTIONGEO_COUNTRYCODE','ACTIONGEO_ADM1CODE','ACTIONGEO_LAT','ACTIONGEO_LONG','ACTIONGEO_FEATUREID',
    'DATEADDED','SOURCEURL'
]